# This is a basic workflow to help you get started with Actions

name: Color of the Day

# Controls when the workflow will run
on:
  # Triggers color reroll at any time matching this pattern
  schedule:
    - cron: 0 0 * * *

  # Run dispatch to update the role upon request
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run Color of the Day
        uses: TinkerStorm/discord-cotd-action@main
        with:
          app-token: "${{ secrets.APP_TOKEN }}"
          guild-id: "684013196700418048"
          role-id: "874695874704449627"
