on:
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    concurrency: auto-update
    strategy:
      matrix:
        include:
          - webhook: INFO_CHANNEL_WEBHOOK
            config: ./info/config.json
          - webhook: README_CHANNEL_WEBHOOK
            config: ./readme/config.json
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          check-latest: true
      - name: Install dependencies
        run: |
          node -v
          npm install
      - name: Run sequence
        run: npm run sequence -- --config ${{ matrix.config }}
        env:
          WEBHOOK_URL: ${{ secrets[matrix.webhook] }}

      - name: Push cache update if any
        run: |
          if [ "$(git status ./cache.json --porcelain)" ]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"

            git add ./cache.json
            git commit -m "auto: Update cache.json"
            git push
          fi